### ISSUE TITLE
subscribe to messages

### ISSUE THREAD

**Issue by t-i-m-o-88** [br-automation-com/PahoMQTT_Library#1]
@patricthysell 
Hello and first of all thank you for the library!
Is it possible that you provide another small example showing how to subscribe to messages?

**Comment by patricthysell** [comment]
Hi,
The implementation uses the standard Paho API, which means, if youre up for trying, you could go for
https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/subasync.html

and adjust it similar to the Sample found in this repo;
- <stdio.h> isnt supported, so use "ar/logger.h" instead
- change all printf() with either ArPahoLogError(), ArPahoLogInfo() or ArPahoLogSuccess(), and remove the linefeeds
- putchar isnt supported either, so youd have to create your own stringbuffer[fixedsize] in the msgarrvd() function and use strncat(), followed by an ArLogSuccess("%s",stringbuffer)
- for the while loop at the end, you could use 
do
{
   PahoMQTT_Sleep(100);
}while(PahoMQTT_IsAline(taskHandle1));

Let me know if this works for you J
cheers, Patric

**Comment by JobFranken** [comment]
Hello,
Hereby a small synchronous subscribe and recieving of messages

```c
 {
    char *topicName  ;
    int topicLength ;
    MQTTClient_message * recvMessage  ;
    
    // subscribe to topics
    MQTTClient_subscribe  ( client ,  TOPIC , 0 );  
        
    while(PahoMQTT_IsAlive(taskHandle1))
    {
        // Recieve all topics 
        MQTTClient_receive  ( client,  &topicName,  &topicLength ,  &recvMessage ,  10  ) ;
    
        if( topicName > 0 )
        {
            ArPahoLogSuccess("Recieved Topic %s with message %s \n", topicName, recvMessage->payload);
            
            MQTTClient_freeMessage  ( &recvMessage ) ;
        }   
        PahoMQTT_Sleep(5000);
    }
}
```

**Comment by t-i-m-o-88** [comment]
Thanks a lot for your examples! I hope that I will find the time to test it in the coming days.
