### ISSUE TITLE
Publish and Subscribe to Multiple Topics in 1 Task

### ISSUE THREAD

**Issue by rynaldi95** [br-automation-com/PahoMQTT_Library#10]
Hi,

I am Rynaldi Maydrian Lauren. I am currently working on a project that is using MQTT to exchange data between different systems, namely Arduino, B&R PLC, and also Unity3D (I use this software to design Augmented Reality program that shows the data acquired by the PLC and Arduino). 

So far, everything has been working well. I have also tried the Multiple Clients with V4.34.0-rev.11 and it is working fine. I have copied the "Sample" program and pasted it as "Sample2" to use it as a second client that publishes a different message to a different topic. I have tried the setup on 4PP065_0571_P74 hardware using N4.34 Automation Runtime. Next time, I will try to use another PLC which is 4PPC70_0702_20B. Thank you for the detailed tutorial to set everything up!

However, I have some questions here:
1. Is it actually possible to subscribe/publish to different topics only in 1 Task?
2. Is it possible to have both publisher and subscriber in 1 Task?

Can I actually define another object of MQTTClient in the  _Sample.c_ file? In the default code, the line `MQTTClient client` creates an instance of the MQTTClient. Is possible to make another instance like `MQTTClient client2`? 

Thank you very much for your help
I am looking forward to hearing from you soon!

Best regards,

Rynaldi Maydrian Lauren

**Comment by rynaldi95** [comment]
Hi!

Sorry but I've just found another problem that I actually can't subscribe to a topic.
Every time I want to subscribe, the PLC gets restarted. I started the thread by setting the `PahoMQTT_Cyclic_0.Resume` to 1.
After getting restarted, the PLC boots in Service mode.

Here is the code for the **Main.c**
`
#include <bur/plctypes.h>

#ifdef _DEFAULT_INCLUDES
	#include <AsDefault.h>
#endif
void secureSampleSubscribe(unsigned long param);


void _INIT ProgramInit(void)
{		
	PahoMQTT_Init_0.EnableLogger = 1;
	PahoMQTT_Init_0.MainThread = (UDINT)secureSampleSubscribe;
	PahoMQTT_Init_0.ThreadParam = (UDINT)Message;
	PahoMQTT_Init_0.SuspendThread = 0;
	PahoMQTT_Init(&PahoMQTT_Init_0);
	
}

void _CYCLIC ProgramCyclic(void)
{
	PahoMQTT_Cyclic(&PahoMQTT_Cyclic_0);
}

void _EXIT ProgramExit(void)
{
	PahoMQTT_Exit();
}

`

And here is the code for the **Sample.c**:
`#ifdef _DEFAULT_INCLUDES
#include <AsDefault.h>
#endif

#include <stdlib.h>
#include <string.h>
#include <PahoMQTT.h>
#include "MQTTClient.h"
#include "ar/logger.h"

#define ADDRESS     "tcp://192.168.0.213:1883"
#define CLIENTID    "SubSample"
#define TOPIC       "outTopic"
#define PAYLOAD     message
#define QOS         1
#define TIMEOUT     10000L

void secureSampleSubscribe(unsigned long param)
{
	do
	{
		MQTTClient client;
		MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
		MQTTClient_message pubmsg = MQTTClient_message_initializer;
		MQTTClient_deliveryToken token;
		//MQTTClient_SSLOptions ssl_opts = MQTTClient_SSLOptions_initializer;
		int rc;
	    
		MQTTClient_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
	    
		conn_opts.keepAliveInterval = 20;
		//conn_opts.reliable = 0;
		conn_opts.cleansession = 1;
		//ssl_opts.enableServerCertAuth = 0;
	       
		//conn_opts.ssl = &ssl_opts;
	    
		if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
		{
			ArPahoLogError("Failed to connect, return code %d\n", rc);
		}
		else
		{
			
			char topicName[20] = "";
			int topicLength ;
			MQTTClient_message * recvMessage  ;
			
			// subscribe
			MQTTClient_subscribe  ( client ,  TOPIC , 0 );  
					
			while(PahoMQTT_IsAlive())
			{
				MQTTClient_receive  ( client,  &topicName,  &topicLength ,  &recvMessage ,  10  ) ;
	    
				if( topicName > 0 )
				{
					ArPahoLogSuccess("Recieved Topic %s with message %s \n", topicName, recvMessage->payload);
					
					MQTTClient_freeMessage  ( &recvMessage ) ;
				}		
			
				PahoMQTT_Sleep(5000);
			}
		}
		MQTTClient_unsubscribe(client, TOPIC);
		MQTTClient_disconnect(client, 10000);
		MQTTClient_destroy(&client);
		
	} while(PahoMQTT_IsReset());
}
`
This code is the example code provided in the SampleNL program, but I modified it a bit since I don't need to have an SSL Connection. Could someone point out what's the problem is?
Thank you in advance :) 

Best regards,

Rynaldi Maydrian Lauren

**Comment by JobFranken** [comment]
Hello Rynaldi,

Yes it is possible that one client subscribes and publisches to more then one topic.  You just have to alter the sample a little.
If you call MQTTClient_subscribe  ( client ,  TOPIC , 0 );   with different topics you could subscribe to more then one.  Its also possible to subscribe with a Topic wildcard to directly recieve more then one. The MQTTClient_receive  ( client,  &topicName,  &topicLength ,  &recvMessage ,  10  ) ; recieves all subscribed topics.
  
The same is valid for the MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token);  When you call this function with different topics the client adds them in a que and will send them.

You can mix them in one task.  Its possible to call the MQTTClient_receive in a faster rate and every x the publisch message.  

With kind regards,
Job Franken

**Comment by rynaldi95** [comment]
Hi @JobFranken!
Thanks for the reply and info!

However, I have just found out another problem. I have no problem in publishing the message with PahoMQTT Lib in both 4PP065_0571_P74 and 4PPC70_0702_20B. But, I have been trying to subscribe to MQTT Topic and it always gives me an error. 
Every time I try to get the Task out of Suspend State with the `PahoMQTT_Cyclic_0.Resume`, the PLC gets restarted and it boots again in **Service Mode**. Could you give me some hint about what's going on and what I should do?

I upload the file here. 
*Sorry that I didn't directly post the file here because I don't know why but when I paste the code, it was not recognized as code, but only as plain text. Therefore, I thought that it is better if I just upload the file instead.

[Sample.txt](https://github.com/br-automation-com/PahoMQTT_Library/files/4971876/Sample.txt)
[Main.txt](https://github.com/br-automation-com/PahoMQTT_Library/files/4971877/Main.txt)

I think it is somehow similar to the thread here #2 . I don't know if this issue is fixed already.

Best regards,

Rynaldi Maydrian Lauren

**Comment by TomasVostrel** [comment]
Hello Rynaldi,

I think you have a problem with the topicName variable in the Sample.c file. The MQTTClient_receive function expects the topicName to be an address of a pointer to a topic.  The function itself allocates the memory for the topic and returns it to the application by setting the pointer.

So not:
`char topicName[20] = "";`

but
`char *topicName = 0;`

Have a nice day,
Tomáš Vostřel
