### ISSUE TITLE
subscribeAsync using MQTTClient_setCallbacks

### ISSUE THREAD

**Issue by rudenko-ks** [br-automation-com/PahoMQTT_Library#2]
Hello!
First of all I express great gratitude for this library. 
Now it very much helps us in the decision of our tasks!
I had a question related to the operation of the program in Asynchronous mode.

I want to implement the program in asynchronous mode. I did based on the examples I found to this library, I studied the comments to functions. First I made a synchronous version. And it works well.

```
while(PahoMQTT_IsAlive(taskHandle2))
	{
		if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
		{
			ArPahoLogError("Failed to connect, return code %d\n", rc);
			PahoMQTT_Sleep(2000);
		}
		else
		{
			statusSubscribe = MQTTClient_subscribe(client, TOPIC, QOS);
			while(MQTTClient_isConnected( client ) && PahoMQTT_IsAlive(taskHandle2))
			{
                                statusReceive = MQTTClient_receive(client, &topicName, &topicLen, &recmsg, TIMEOUT);
				if (topicLen != 0)
				{
					brsmemset((UDINT) topicDataStr, 0, brsstrlen((UDINT) topicDataStr));
					
					brsstrcpy((UDINT) topicNameStr, (UDINT)topicName ); 
					brsmemcpy((UDINT) topicDataStr, (UDINT) recmsg->payload, (UDINT) recmsg->payloadlen);
					topicLen = 0;
					MQTTClient_free(topicName);
					MQTTClient_freeMessage(&recmsg);
				}
			}
    
		}
	}
```

Then I tried to implement the work in asynchronous mode. Code:

```
#include <bur/plctypes.h>

#ifdef _DEFAULT_INCLUDES
	#include <AsDefault.h>
#endif

#include <stdlib.h>
#include <string.h>
#include <PahoMQTT.h>
#include "MQTTClient.h"
#include "ar/logger.h"

#define ADDRESS     "tcp://192.168.0.134:1883"
#define CLIENTID    "ExampleClientSubAsync"
#define TOPIC       "broker/status"
#define PAYLOAD     "ExampleClientSubAsync"
#define QOS         1
#define TIMEOUT     2000L

volatile MQTTClient_deliveryToken deliveredtoken;

_LOCAL BOOL GoGoGo;
_LOCAL int receveMsg;
_LOCAL int statusCallback;
_LOCAL STRING statusCallbackStr[80];
_LOCAL int statusSubscribe;
_LOCAL STRING statusSubscribeStr[80];
_LOCAL STRING connlostStr[255];
_LOCAL STRING topicNameStr[80];
_LOCAL STRING topicDataStr[80];

_LOCAL int dtok;

void delivered(void *context, MQTTClient_deliveryToken dt)
{
	dtok++;
	receveMsg = 1;
}

int msgarrvd(void* context, char* topicName, int topicLen, MQTTClient_message* message)
{
	if (topicName > 0)
	{
		brsmemset((UDINT) topicDataStr, 0, brsstrlen((UDINT) topicDataStr));
					
		brsstrcpy((UDINT) topicNameStr, (UDINT)topicName ); 
		brsmemcpy((UDINT) topicDataStr, (UDINT) message->payload, (UDINT) message->payloadlen);
		MQTTClient_free(topicName);
		MQTTClient_freeMessage(&message);
	}
	receveMsg = 2;
	return 1;
}

void connlost(void* context, char *cause)
{
	ArPahoLogInfo("\nConnection lost\n");
	ArPahoLogInfo("     cause: %s\n", cause);
	if (cause == NULL)
		brsstrcpy((UDINT) connlostStr, (UDINT)"NULL" ); 
	else brsstrcpy((UDINT) connlostStr, (UDINT)cause );
	receveMsg = 3;
}

void subscribeAsync(unsigned long param)
{
	MQTTClient client;
	MQTTClient_connectOptions conn_opts = MQTTClient_connectOptions_initializer;
	int rc;
	
	MQTTClient_message pubmsg = MQTTClient_message_initializer;
	MQTTClient_deliveryToken token;
	
	MQTTClient_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;

	statusCallback = MQTTClient_setCallbacks(client, NULL, connlost, msgarrvd, delivered);
	
	while(PahoMQTT_IsAlive(taskHandle2))
	{
		if ((rc = MQTTClient_connect(client, &conn_opts)) != MQTTCLIENT_SUCCESS)
		{
			ArPahoLogError("Failed to connect, return code %d\n", rc);
			PahoMQTT_Sleep(2000);
		}
		else
		{
			ArPahoLogInfo("SUBSCRIBING to topic %s\nfor client %s using QoS%d\n\n"
				"Press Q<Enter> to quit\n\n", TOPIC, CLIENTID, QOS);
			statusSubscribe = MQTTClient_subscribe(client, TOPIC, QOS);

			while(MQTTClient_isConnected( client ) && PahoMQTT_IsAlive(taskHandle2))
			{
				if (GoGoGo)
				{
					pubmsg.payload      = PAYLOAD;
					pubmsg.payloadlen   = strlen(PAYLOAD);
					pubmsg.qos          = QOS;
					pubmsg.retained     = 0;
					deliveredtoken = 0;

	 				MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token);
					PahoMQTT_Sleep(1000);
				}
			}
		}
	}
	MQTTClient_unsubscribe(client, TOPIC);
	MQTTClient_disconnect(client, 10000);
	MQTTClient_destroy(&client);
}
```

If the program is running in synchronous mode and I send data via MQTTLens (https://github.com/sandro-k/MQTTLensChromeApp), the function

`MQTTClient_receive (client, & topicName, & topicLen, & recmsg, TIMEOUT);`

runs and receives data from the broker. And topicName contains the name of the topic on the broker, and topicLen returns the length of the topic name.
But if I try the program work in the asynchronous mode, I do not get any data from the broker and MQTTClient_setCallbacks does not work, although they are published in the topic using MQTTLens.
If I publish the data myself from the program code (if set flag GoGoGo):

```
while(MQTTClient_isConnected( client ) && PahoMQTT_IsAlive(taskHandle2))
{
    if (GoGoGo)
    {
        pubmsg.payload      = PAYLOAD;
        pubmsg.payloadlen   = strlen(PAYLOAD);
        pubmsg.qos          = QOS;
        pubmsg.retained     = 0;
        deliveredtoken = 0;        
        MQTTClient_publishMessage(client, TOPIC, &pubmsg, &token);
        PahoMQTT_Sleep(1000);
    }
}
```

then MQTTClient_setCallbacks executes and returns the data that I have published. But if I use third-party clients (example, for Windows), what they publish, my program on B+R does not see.

By the method of the samples it was possible to find out that MQTTClient_setCallbacks was working and the function msgarrvd () returned data from other clients if I added the **MQTTClient_yield ()** method to the code;
```
while(MQTTClient_isConnected( client ) && PahoMQTT_IsAlive(taskHandle2))
{
    if (GoGoGo)
    {
        ........
    }

    MQTTClient_yield();
}
```
And then MQTTClient_setCallbacks started working and started receiving messages that I published via MQTTLens. But here's another point, for some reason topicLen is always 0. However, in the topicName and message, the correct data is passed.

But, as I understand it, if I use **MQTTClient_yield ()**, then this is already the synchronous mode of the program.

Maybe I'm doing something wrong? Any ideas?
Can you check this code yourself and, if possible, make your edits and use third-party clients to publish messages when checking?

Main.c I took from your example here
https://github.com/br-automation-com/PahoMQTT_Library/blob/master/SampleNL/Main.c
There I changed only
PahoMQTT_Init_0.SuspendThread from 1 to 0.

**Comment by patricthysell** [comment]
Hi @rudenko-ks !
Sorry I havent answered this issue, I simply haven't seen it until now. I will make sure to have a more watchful eye on the issues raised here in future. 

Im quite sure you are doing everything right,

I havent been testing the specifics of the MQTT API myself until recently, and after having read through the Paho documentation (https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/_m_q_t_t_client_8h.html#a8ad3d29864a9ca08202b0832e0f6678e), I am also using `MQTTClient_yield()` in the MainThread.

Actually, after the first year of implementations, I can see that most applications follow the almost same pattern, and so I have built a Library - PahoClient which implements the Asynchronous thread with callbacks and subscriptions, and basically only offers two functions - PahoPublish and PahoSubscribe. I will make this Libary open-source so you can adapt it after your needs, but I think it should basically cover most use cases (I have seen so far), and make it possible to use the Paho Library in an IEC environment, I need to do some more testing on it, and write some documentation, but I guess I can have something ready within november, lets see.

Ok keep it up, and thanks for posting these observations.
cheers

**Comment by chzeinar** [comment]
Thank You Patric!
A simple library with asynchronous Publish and Subscribe would be very very helpful!

I am a teacher at a technical school in Vienna/Austria and we'd like to connect our lab (PLCs, Arduinos, ABB-Robots, Raspberrys,..) with MQTT. I have no troubles to publish messages with PahoMQTT-Lib., but whe I try the sample with receiving messages, my C70 (AR K4.26) gets into booting mode and can only be resetted by the reset-button, Diagnosis mode, restart and so on.

Thank You

**Comment by patricthysell** [comment]
Its rather strange that you get these errors, subscribe definitively works.
Please get in contact with me via LinkedIn (on my profile) then I can send you a preliminary version of the Client library, and we can have a look at the problems you have run into. (will update this thread with the results)

**Comment by patricthysell** [comment]
we moved this library over to 
[https://github.com/br-automation-com/paho.mqtt.c-ar/](https://github.com/br-automation-com/paho.mqtt.c-ar/)
that definitively has a simple sample/subscribe functionality with the IotMqtt function block library
