### ISSUE TITLE
Problem with the Library

### ISSUE THREAD

**Issue by karakal** [br-automation-com/PahoMQTT_Library#4]
Hello,

My setup:
Automation Studio 4.5
X20CP0482
AR: B4.45
MQTT-Server: mosquitto running locally

I try to use this library with a CP0482 with automation runtime B4.45. I use static linking as described in the readme.MD
I used your sample programs to test the library. Everything is compiling and linking and transfering.

I have two issues with this:
When I am deploying to the physical system, only the LOG-System is initialized, no connection is ever made, no debug point inside is ever reached.

When I am using it in the Simulation, i reach the debug points, but no connection is possible to the MQTT-Server. I just get a connection refused.

I followed all your steps but I don't know what else I should try...

**Comment by karakal** [comment]
Another bit of information:
All network related topics are in order. I can reach the MQTT-server from another computer in the same network. I can reach the X20 CPU and no firewall is activated anywhere....

**Comment by Namdevrj** [comment]
> Hello,
> 
> My setup:
> Automation Studio 4.5
> X20CP0482
> AR: B4.45
> MQTT-Server: mosquitto running locally
> 
> I try to use this library with a CP0482 with automation runtime B4.45. I use static linking as described in the readme.MD
> I used your sample programs to test the library. Everything is compiling and linking and transfering.
> 
> I have two issues with this:
> When I am deploying to the physical system, only the LOG-System is initialized, no connection is ever made, no debug point inside is ever reached.
> 
> When I am using it in the Simulation, i reach the debug points, but no connection is possible to the MQTT-Server. I just get a connection refused.
> 
> I followed all your steps but I don't know what else I should try...

Hi,

I am facing same issue like compilation is successful, simulation is in run mode but connection is not successful. I am working on Automation studio 4.6 with AR:B4.63 and MQTT library V4.45.
Is there any other settings needs to be done, as i followed steps mentioned in the link for sample program. 
https://github.com/br-automation-com/PahoMQTT_Library/blob/master/README.md

**Comment by patricthysell** [comment]
Sorry for the late reply - we moved this library over to 
[https://github.com/br-automation-com/paho.mqtt.c-ar/](https://github.com/br-automation-com/paho.mqtt.c-ar/)

Here both ArSim and Compact-S are supported
