### ISSUE TITLE
MQTT library integration error with B&R studio

### ISSUE THREAD

**Issue by Namdevrj** [br-automation-com/PahoMQTT_Library#5]
Hi, 

I am working on automation studio 4.6 with AR:B4.63 and paho MQTT library V4.45.

Currently i am able to integrate and compile the example as mentioned in readme as per the below link.
https://github.com/br-automation-com/PahoMQTT_Library/blob/master/README.md

But during simulation, i am not able to connect to MQTT server and same is reflected in MQTT_LOG. Is there any other setting that i am missing to set in the B&R studio. Please provide your valuable inputs.

![Capture](https://user-images.githubusercontent.com/59044715/71153279-b8262800-225e-11ea-9760-9cd615fb5160.PNG)

**Comment by stephb59** [comment]
Hi 
I had similar problems trying make it work through simulation.
I contacted B&R and they suggests going forward with real plc.
This is then working and i am now able to reach MQTT server and sending values.
Regards.
Stéphane

**Comment by JobFranken** [comment]
> Hi
> I had similar problems trying make it work through simulation.
> I contacted B&R and they suggests going forward with real plc.
> This is then working and i am now able to reach MQTT server and sending values.
> Regards.
> Stéphane

Hello,

Stéphane is correct, the current implementation is only working on real hardware. 
For the connection part we rely on functionality which is not available in the Sim plc. 

With kind regards,
Job Franken

**Comment by Namdevrj** [comment]
Whether B&R studio supports Paho Javascript client integration. My requirement is to transfer data using MQTT to cloud using web application. In this case we need web socket implementation.
So whether B&R supports the Javascript for the same.

**Comment by patricthysell** [comment]
we moved this library over to 
[https://github.com/br-automation-com/paho.mqtt.c-ar/](https://github.com/br-automation-com/paho.mqtt.c-ar/)
That works with ArSim
