### ISSUE TITLE
MQTT paho client library support with B&R tool using javascript

### ISSUE THREAD

**Issue by Namdevrj** [br-automation-com/PahoMQTT_Library#6]
Whether B&R studio supports Paho Javascript MQTT client integration. My requirement is to transfer data using MQTT to cloud using web application. In this case we need web socket implementation.
So whether B&R supports the Javascript for the same.

**Comment by patricthysell** [comment]
No JavaScript is not supported in Automation Studio, as Automation Runtime has no V8 JavaScript engine running
