### ISSUE TITLE
Paho MQTT library integration issue with X20CP3586 B&R PLC

### ISSUE THREAD

**Issue by Namdevrj** [br-automation-com/PahoMQTT_Library#7]
Hello,

My setup:
Automation Studio 4.6
X20CP3586
AR: B4.63
MQTT-Server: mosquitto running locally.

We are working on B&R PLC X20CP3586, in which we are integrating paho MQTT library with version 4.45 provided here and the below is the link:
https://github.com/br-automation-com/PahoMQTT_Library

But the issue is, we followed all the steps mentioned in the link, still we are not able to have a connection with MQTT broker which is currently Masquitto broker which is configured locally.

So is there any other configuration required. Whether X20CP3586 supports paho MQTT library or new version of library is required for B&R PLC. If any other version of paho MQTT library is required then can you please guide us.

**Comment by Namdevrj** [comment]
Can you please mention the environment that you were using like automation studio version, B&R PLC on which  you were executing. Because the support for paho MQTT library is tested on only few hardware's. I tried with above mentioned versions, but still I will try with your approach once again as I already tried with those options.

**Comment by Namdevrj** [comment]
I tried above example with mentioned environment, but still i am not getting messages on localhost.
In my case I am using MQTTlens as a broker and my B&R PLC is the client. I tried with by changing address to "tcp:/localhost:1883" and with ip address on which my PLC is connected.
Any other changes required or my PLC is not supporting those libraries of paho MQTT. I am using B&R PLC X20CP3586 on automation studio V4.6 and AR 4.63

**Comment by stephb59** [comment]
Hi Here are details about our configuration
cpu harware 4PPC70_0702_20B
automation runtime D4.34
broker mosquitto
automation studio V4.3.9.141

**Comment by JobFranken** [comment]
> Any other changes required or my PLC is not supporting those libraries of paho MQTT. I am using B&R PLC X20CP3586 on automation studio V4.6 and AR 4.63

We tested a few Intel SG4 targets and ARM SG4 targets.  Both types should work without any problems on all similar CPU types. Additionally the tested X20CP158x CPU is the same CPU type as your X20CP358x. It is also an Intel SG4 target

**Comment by Namdevrj** [comment]
> Hi Here are details about our configuration
> cpu harware 4PPC70_0702_20B
> automation runtime D4.34
> broker mosquitto
> automation studio V4.3.9.141

Whether paho MQTT libraries are specific to PLC hardware and automation studio versions. As with above mentioned environment I am not able to publish/subscribe on B&R PLC. Whether for B&R PLC X20CP3586, we need specific libraries.

**Comment by Namdevrj** [comment]
> > Any other changes required or my PLC is not supporting those libraries of paho MQTT. I am using B&R PLC X20CP3586 on automation studio V4.6 and AR 4.63
> 
> We tested a few Intel SG4 targets and ARM SG4 targets. Both types should work without any problems on all similar CPU types. Additionally the tested X20CP158x CPU is the same CPU type as your X20CP358x. It is also an Intel SG4 target
> 
> Could you upload your logbook to see what the lib is doing.

Attached folder have some log files. Can you please check for details and let me know for any other information.

[X20CP3586.zip](https://github.com/br-automation-com/PahoMQTT_Library/files/4169447/X20CP3586.zip)

**Comment by Namdevrj** [comment]
> > Any other changes required or my PLC is not supporting those libraries of paho MQTT. I am using B&R PLC X20CP3586 on automation studio V4.6 and AR 4.63
> 
> We tested a few Intel SG4 targets and ARM SG4 targets. Both types should work without any problems on all similar CPU types. Additionally the tested X20CP158x CPU is the same CPU type as your X20CP358x. It is also an Intel SG4 target
> 
> Could you upload your logbook to see what the lib is doing.

#define ADDRESS    "tcp://localhost:1883"
#define CLIENTID    "ExampleClientPub"
#define TOPIC       "test"
#define PAYLOAD     Message
#define QOS         1
#define TIMEOUT     10000L

This is my setting in sample program for localhost on PLC which is connected by ethernet for upload. Anything missing.

**Comment by JobFranken** [comment]
> Any other changes required or my PLC is not supporting those libraries of paho MQTT. I am using > #define ADDRESS    "tcp://localhost:1883"
> This is my setting in sample program for localhost on PLC which is connected by ethernet for upload. Anything missing.

Your logbook is empty ( only seeing it start ).  Please make sure its out of its Suspend state. You can also set the "PahoMQTT_Init_0.SuspendThread" to zero. 

- The ADDRESS localhost could never work. The MQTT Server is running on your Laptop so please use the Laptop IP from the network interface that is connected to the PLC.
- If the PLC cannot connect to the Laptop check your Laptop Firewall settings.
