### ISSUE TITLE
Unable to build the project with PahoMQTT library

### ISSUE THREAD

**Issue by Vamalgise** [br-automation-com/PahoMQTT_Library#9]
Hello
I am trying to implement PahoMQTT version V4.45.0-rev.11: Automation Runtime 4.45.
I tried with Automation Studio V 4.4 and Automation Studio V 4.7. I could not update AS 4.4 to as 4.45 as installer constantly gave me mistakes.

Anyhow I follow the instructions and get this:
![pahoMqttErrors](https://user-images.githubusercontent.com/62007744/76291508-ed6a7100-62b5-11ea-90c7-a9274fe3d31a.PNG)

I do not understand what I do wrong, but I guess that version compatibility might be the answer.
Can I use library V 4.45 at all with Automation Studio V 4.72 and PLC Automation Runtime C4.72?
Also is it enough to just change the AR in CPU properties or Automation Studio itself must also be changed?

Thanks!

**Comment by JobFranken** [comment]
Hello,

Are you using an Compact-S CPU ? 
The V4.45.0 is only avialable as static library for ARM targets, see "Using Multiple Clients (Static Linking)"

Please try the V4.34.0-rev.11 if you dont want to use the static linking. 

With kind regards,
Job Franken

**Comment by Vamalgise** [comment]
Thank you JobFranken,

I chose runtime 4.34 in CPU properties and library V4.34.0-rev.11. Project compiles and publishes the message, I can see it in RabbitMQ.
